- pytket/extensions/quantinuum/backends/quantinuum.py
- setup.py
- tests/backend_test.py
- tests/conftest.py
As I currently don't have access to any gate fidelity information for the devices, I assume perfect fidelity. This can obviously easily be changed in the future.
Note that I removed the `ZZPhaseToRz` pass when `FullPeephole` is run, as the KAK should already do the optimal thing.
> [feature] ZZPhase support for devices that support it

- pytket/extensions/quantinuum/backends/quantinuum.py
Added the `ZZPhaseToRz` pass to the `default_compilation_pass` at optimisation_level=2 per the recent issue https://github.com/CQCL/pytket-quantinuum/issues/48 . 
If there is anything else to be added let me know.
> add missing ZZPhaseToRz pass

- .github/workflows/build_and_test.yml
This is a new way to publish to github pages that doesn't use the special `gh-pages` branch.
It is still officially "beta" but seems to work.
Requires a modification to the repo "Pages" settings to enable it. (I modified the settings to test it, and have now reverted them, but will switch back once this is merged).
Tested here: https://github.com/CQCL/pytket-quantinuum/actions/runs/3468800329
Docs successfully uploaded: https://cqcl.github.io/pytket-quantinuum/api/index.html
> Use `actions/deploy-pages` to publish docs

- pytket/extensions/quantinuum/backends/api_wrappers.py
- pytket/extensions/quantinuum/backends/quantinuum.py
- tests/backend_test.py
When the H2 is released we should add more tests for it; this PR is just to make sure the existing tests continue to work. (Also add H2-1 to the "offline" API, and remove an unused variable.)
> Ensure tests are ready for H2

- .github/workflows/docs/requirements.txt
Preventing an upgrade to the new 1.0+ version of sphinx_book_theme for now
I think we should make documentation compatible with sphinx_book_theme v1.0+ for the next release
> prevent docs theme upgrade for now

- docs/api.rst
- docs/changelog.rst
- pytket/extensions/quantinuum/__init__.py
- pytket/extensions/quantinuum/backends/__init__.py
- pytket/extensions/quantinuum/backends/quantinuum.py
- setup.py
- tests/api1_test.py
- tests/backend_test.py
- tests/test-requirements.txt
For "experimental" read "not working". However, at least `QuantinuumBackend.submit_program()` with valid QIR bitcode _is_ working, and the plumbing is there for `process_circuits()` (though if you try to use it now you'll get a warning and the submission will almost certainly fail).
> Experimental QIR support

- pytket/extensions/quantinuum/backends/quantinuum.py
- tests/backend_test.py
Test fails with:
```
self = <pytket.qir.conversion.conversion.QirGenerator object at 0x7fc3ec940c70>, command = PhasedX(3.5, 0.5) node[0];
def _rebase_command_to_gateset(self, command: Command) -> Optional[Circuit]:
"""Rebase to the target gateset if needed."""
optype = command.op.type
params = command.op.params
args = command.args
if optype not in self.module.gateset.base_gateset:
circuit = Circuit(self.circuit.n_qubits, self.circuit.n_bits)
>           circuit.add_gate(optype, params, args)
E           RuntimeError: Circuit does not contain unit with id: node[0]
../env/lib/python3.10/site-packages/pytket/qir/conversion/conversion.py:292: RuntimeError
```
> Change warning message

- pytket/extensions/quantinuum/backends/quantinuum.py
- tests/api1_test.py
- tests/backend_test.py
Add an extra field to the `ResultHandle` to track this. While here, make extraction of values from result handles a little less error-prone by adding and using dedicated methods.
> Truncate results from QIR processing to desired width

- .github/workflows/build-test
Fix a typo in the `build-test` script when checking whether to run or not the integration tests.
> Typo when testing for the INTEGRATION flag

- docs/changelog.rst
- pytket/extensions/quantinuum/backends/quantinuum.py
- tests/unit/api1_test.py
Currently the held architecture labels UnitID with "node".
However, the `FlattenRelabelRegistersPass` relabels all Circuit qubit to label "q".
This PR corrects this mismatch.
> Store FullyConnected("q") in BackendInfo

- pytket/extensions/quantinuum/backends/leakage_gadget.py
To fix -> https://github.com/CQCL/pytket-quantinuum/issues/192
We use spare device qubits for leakage detection. We also reuse these spare device qubits for multiple leakage detections if needed (though reusing each qubit as few times as possible). I accidentally repeated the logic for "resetting" this spare device qubit for also assigning Bit to send measurement results to - this PR makes sure all leakage detection have their own Bit.
> Always measure leakage detection result to a new Bit

- docs/changelog.rst
- pytket/extensions/quantinuum/backends/quantinuum.py
- tests/integration/backend_test.py
Fixes #213 .
Integration tests running here: https://github.com/CQCL/pytket-quantinuum/actions/runs/6036474819 .
> Ignore erased scratch bits when constructing `ResultHandle`

- pytket/extensions/quantinuum/backends/quantinuum.py
I noticed that the `check_examples` workflow was taking longer than usual on #215 . It may be unrelated, but for large QASM files this optimization could make a difference.
Integration tests running here: https://github.com/CQCL/pytket-quantinuum/actions/runs/6049542632 /
> Improve efficiency of check

- tests/integration/backend_test.py
I don't think I can update the pytket-qir version in `tests/test-requirements.txt` because 0.2.1rc1 requires pytket >= 1.20.0rc2 so would not work with 1.19.1. But I don't think there is a version that is compatible with both...?
> Disable QIR for two tests.

- docs/changelog.rst
- pytket/extensions/quantinuum/backends/quantinuum.py
- tests/integration/backend_test.py
> Set default two-qubit gate when compilation config is provided without one

- pytket/extensions/quantinuum/backends/api_wrappers.py
#247 slightly changes the default behaviour of `QuantinuumBackend`, namely the default `api_handler`, which uses `MemoryCredentialStorage` for storing credentials, won't use the cached login email address even if the user did cache their email using `set_quantinuum_config`. This means email will always be asked if default `api_handler` is used. I suspect that many users won't like this change.
The intent of this PR is to temporarily revert this behaviour change until we agree on what the default behaviour should be.
> Allow MemoryCredentialStorage to access cached username

- docs/changelog.rst
- docs/intro.txt
- pytket/extensions/quantinuum/backends/quantinuum.py
- tests/integration/backend_test.py
Added an extra `RemoveRedundancies` pass to levels 1 and 2 in the default passes to get rid of Rz gates before measurement.
closes https://github.com/CQCL/pytket-quantinuum/issues/265.
> Add an extra `RemoveRedundancies` pass for levels 1 and 2.

- pytket/extensions/quantinuum/backends/quantinuum.py
This potentially saves a large number of calls to the remote API.
Also make `_dict_to_backendinfo()` take a copy of its argument to avoid mutating it.
> Cache results of QuantinuumBackend._available_devices()

- .github/workflows/docs/conf.py
- .github/workflows/docs/requirements.txt
- pytket/extensions/quantinuum/backends/api_wrappers.py
- pytket/extensions/quantinuum/backends/leakage_gadget.py
- pytket/extensions/quantinuum/backends/quantinuum.py
We now use the `sphinx-autodoc-typehints` extension. With this types can be inferred from the source code so we don't need to specify them twice anymore.
> Remove redundant type declarations from docstrings

- docs/changelog.rst
- pytket/extensions/quantinuum/backends/quantinuum.py
- tests/integration/backend_test.py
Closes #291 .
(The argument is still needed for the emulators, but this ensures it won't accidentally incur costs.)
> Make `QuantinuumBackend.cost()` safe

- .github/workflows/build_and_test.yml
- docs/changelog.rst
- docs/intro.txt
- pytket/extensions/quantinuum/__init__.py
- pytket/extensions/quantinuum/backends/__init__.py
- pytket/extensions/quantinuum/backends/quantinuum.py
- setup.py
- tests/conftest.py
- tests/integration/local_emulator_test.py
- tests/unit/api1_test.py
When pytket-quantinuum is installed with the `pecos` option (`pip install pytket-quantinuum[pecos]`), local-emulator backends become available.
For every hardware device detected as available, a local-emulator device is created, having the same name with "LE" appended. This device presents the same API as the actual device (with the exception of a few methods that are not available), but circuit execution is emulated (noiselessly) on the user's machine using PECOS.
Because of current limitations in pytket-phir, functionality is limited: circuits containing classical operations or WASM are not supported. Support for these will be added in due course. Noise emulation will also be added as and when the real devices' noise information becomes available over the API.
I've added a section to …
> Add local-emulator backends as optional feature

- docs/api.rst
Add two credential storage classes to API doc
Resolves #290
> Add credential_storage module to API doc

- .github/workflows/build_and_test.yml
- docs/changelog.rst
- docs/intro.txt
- setup.py
- tests/integration/local_emulator_test.py
Some previous "expected fails" now pass, but more bugs exist -- added separate "expected fail" tests for these.
Now the pecos option works with Python 3.12, so remove the note about this in the documentation.
Closes #330 .
> Update pytket_pecos requirement to 0.1.9 and update classical tests

- pytket/extensions/quantinuum/backends/quantinuum.py
Some internal devices don't have this attribute, so allow for it to be absent.
> Don't raise an exception if a device doesn't have a "system_type".

- docs/changelog.rst
- setup.py
- tests/integration/local_emulator_test.py
Update to latest pytket-pecos, which has in turn been updated to latest pytket-phir, which fixes a couple of bugs. Remove "expected failure" annotation from some tests.
Closes #339 .
> Update to pytket-pecos 0.1.10

- docs/changelog.rst
- pytket/extensions/quantinuum/backends/quantinuum.py
- tests/integration/local_emulator_test.py
Pass the circuit's bits to the constructor of the `BackendResult`.
Fixes #342 .
> Fix handling of results in local emulator with non-default classical registers

- docs/changelog.rst
- docs/intro.txt
- pytket/extensions/quantinuum/backends/quantinuum.py
- setup.py
- tests/integration/local_emulator_test.py
Update to latest pytket-pecos and add WASM support to local emulators. Add tests. Update docs.
Closes #344 .
> Add WASM support to local emulators

- tests/integration/backend_test.py
The issue with noisy QIR simulation seems to be resolved, at least on QA. Therefore we can re-enable this test.
Closes #276 .
> Remove xfail for QIR noise test.

- .github/workflows/build_and_test.yml
- docs/changelog.rst
- setup.py
- tests/test-requirements.txt
This ensures the latest version of quantum-pecos (0.5.0.dev8).
Also update the version of llvmlite used in tests. This enables testing with Python 3.12 and closes #327 .
> Update to pytket-pecos 0.1.15

- docs/changelog.rst
- docs/intro.txt
- pytket/extensions/quantinuum/backends/api_wrappers.py
- pytket/extensions/quantinuum/backends/quantinuum.py
- tests/conftest.py
- tests/integration/backend_test.py
Previously we were looking only for "Rxxyyzz" as the gate name, not "TK2".
Also improve the default compilation passes when targeting this gate.
> Add support for TK2 gate

- pytket/extensions/quantinuum/backends/quantinuum.py
- tests/unit/api1_test.py
Since we don't (yet) have this information in the API, hard-code it to 32 if the number of qubits is <= 32 and 64 otherwise.
> Set classical register width based on qubit count

- docs/changelog.rst
- docs/intro.txt
- pytket/extensions/quantinuum/backends/quantinuum.py
- tests/integration/backend_test.py
Set both `no-opt` and `noreduce` to `True` to prevent any changes to the submitted circuit. It is assumed that the submitted circuit is what is desired to be run.
(It's still possible for these options to be overridden by providing an `options` dictionary to `process_circuits()` or `submit_program()`, but this is very much opt-in for those who know what they're doing.)
> Remove `no_opt` and `allow_2q_gate_rebase` options

- docs/changelog.rst
- setup.py
- tests/integration/local_emulator_test.py
This brings in better support for classical operations on the local emulators.
> Update pytket-pecos to 0.1.24

- pytket/extensions/quantinuum/backends/api_wrappers.py
When using this library, it is sometimes useful to be able to define a custom offline API implementation with different devices which includes the devices of the base implementation. This commit splits those devices out into a constant that can be referred to by other code.
> feat: Offline device list constant

- docs/changelog.rst
- pytket/extensions/quantinuum/backends/leakage_gadget.py
- tests/unit/leakage_detection_test.py
Currently if an input Circuit has the same number of qubits as the Device then Leakage Detection throws an error on the premise that there are no spare qubits. With this PR, leakage detection now reuses measured circuit qubits with no further gates to perform leakage detection with.
> Reuse Circuit Qubits when adding Leakage Detection

- tests/integration/backend_test.py
I don't think it makes sense to have a test that fails if one happens to have `matplotlib` installed.
> Remove unreliable test.

- docs/changelog.rst
- setup.py
> Update to pytket-pecos 0.1.27

- docs/changelog.rst
- pytket/extensions/quantinuum/backends/quantinuum.py
- tests/unit/api1_test.py
Until https://github.com/CQCL/tket/issues/1445 is fixed in pytket.
Works around #451 .
> Temporarily restrict maximum classical register width to 32

- _metadata.py
- docs/changelog.rst
The main point of this release is to require (via pytket-pecos version bump) a version of pytket-phir (0.7.3) that will handle 64-bit classical operations, which will be necessary after https://github.com/CQCL/tket/pull/1456 finds its way to a pytket release.
> Update version and changelog for 0.35.0 release.

- pytket/extensions/quantinuum/backends/api_wrappers.py
This should cause no change to behaviour, but ensures that when partial results retrieval becomes the default we are not surprised by it.
> Don't use partial results.

- tests/integration/backend_test.py
Necessary since #472 requires authentication to construct `QuantinuumBackend`.
> Skip test needing access to authenticated backend when not running remote tests

- _metadata.py
- docs/changelog.rst
- pytket/extensions/quantinuum/backends/quantinuum.py
- setup.py
- tests/integration/backend_test.py
- tests/integration/local_emulator_test.py
- tests/unit/offline_backend_test.py
> update pytket 1 31 0

- tests/integration/backend_test.py
Fixes https://github.com/CQCL/pytket-quantinuum/issues/492
The QIR submitted by this testcase contains four cregs, each containing 5 bits. This is an expected change in how the result is reported.
> [fix] update number of bits in result to fix test

- pytket/extensions/quantinuum/backends/quantinuum.py
- setup.py
Replaces the use of a lambda with a constant value with a constant float. This change will make the default serialization pass for the backend serializable.
None
> feat: Use float for ZZPhase in DecomposeTK2

- pytket/extensions/quantinuum/backends/quantinuum.py
Add warning when using process_circuit without language argument and fixes https://github.com/CQCL/pytket-quantinuum/issues/496
> add warning for default language

- pytket/extensions/quantinuum/backends/quantinuum.py
- tests/unit/offline_backend_test.py
Rather than fetching the 2qb gate of devices on backend construction, this commit changes the behavior of the backend to only fetch devices once the 2qb gate is requested and caches the value as a cached_property using a decorator. As a side effect it removes the need for the user to log in to construct a backend.
Changes to tests that were required due to the backend now requiring credentials to construct have been reverted.
Tangentially related to https://github.com/CQCL/pytket-quantinuum/issues/504
> feat: Lazily load 2qb gate

- .github/workflows/build_and_test.yml
- .github/workflows/check-examples.yml
- .github/workflows/docs.yml
- .github/workflows/lint.yml
The `macos-12` runner is being removed soon; `macos-latest` is currently `macos-14`. Also update to `ubuntu-24.04` a.k.a. `ubuntu-latest` while we're here.
(Will update names of "required checks" after approval.)
> Update runners used on CI

- docs/changelog.rst
- pytket/extensions/quantinuum/backends/quantinuum.py
- tests/integration/backend_test.py
Planned for release in early November. If we need to do a hotfix release before then, we may want to revert this change. But I'd like to merge it to `main` early to get maximal testing.
> Use QIR by default for program submission

- docs/api.rst
- docs/index.rst
- pytket/extensions/quantinuum/backends/credential_storage.py
> Update docstrings in credential_storage.py

- docs/changelog.md
- pytket/extensions/quantinuum/backends/quantinuum.py
- tests/integration/backend_test.py
The automatic leakage detection tries to maximise parallelism by using as many spare device qubits as possible for performing leakage detection. Currently when passing `leakage_detection=True` to `process_circuit/s`, it automatically assumes that the user wants to make use of all qubits. This PR adds a new kwarg to `pytket-quantinuum` `n_leakage_detection_qubits` that allows the user to specify fewer qubits. 
> Set number of qubits for leakage detection

- docs/changelog.md
- pytket/extensions/quantinuum/backends/quantinuum.py
- tests/unit/convert_test.py
> Bugfix/`allow implicit swaps` not handled correctly

- .github/workflows/build_and_test.yml
The docs build is failing in the relase workflow do to the wheel not being properly installed. I've fixed this by running pip within the poetry env as I've done in https://github.com/CQCL/pytket-qiskit/pull/408
fixes #531
> fix: bad poetry install in docs build

- .github/workflows/build_and_test.yml
Another fix to the docs build on release workflow. Looks like I missed a line in #532 
closes #531
> fix: failing docs build

- docs/changelog.md
- pytket/extensions/quantinuum/backends/quantinuum.py
Tested locally with pytket 1.35.0rc0.
> Allow circuits containuing `OpType.ClExpr` operations

- pytket/extensions/quantinuum/backends/api_wrappers.py
- pytket/extensions/quantinuum/backends/quantinuum.py
Fixes the usage of the api handler in the available_devices method by re-using the session of the real handler rather than making a fresh session in the backend.
This will also make it easier to write alternative QuantinuumAPI implementations as a side effect.
Resolves https://github.com/CQCL/pytket-quantinuum/issues/504
> fix: Use API handler for available devices

- docs/index.md
Minor fix. After #546 the table had an invalid number of columns and the `RemoveBarriers` pass didn't show up. Should be fixed now.
Fixed the pytket-qiskit one in https://github.com/CQCL/pytket-qiskit/pull/421
> docs: fix invalid table in docs

- docs/index.md
No longer needed... See https://github.com/CQCL/tket/pull/1721
> docs: remove `_tket` link

- docs/changelog.md
- pytket/extensions/quantinuum/backends/quantinuum.py
- setup.py
- tests/integration/backend_test.py
> Remove `Phase` operations when compiling for backends

- setup.py
After the pytket 2.0 release we should be able to change this to ">= 2.0.0" and remove the handling of, and tests involving, `ClassicalExpBox` in this repo.
> Constrain to pytket 1.x.

- docs/changelog.md
- pytket/extensions/quantinuum/backends/quantinuum.py
QuantinuumBackend's `process_circuits` and `submit_program` now accept a `max_cost` parameter that is passed along to the remote Quantinuum systems. (It's ignored for the local emulator.)
(No related issues.)
> Add max_cost parameter to process_circuits / submit_program

- docs/changelog.md
- pytket/extensions/quantinuum/backends/quantinuum.py
`_parse_status()` already extracts some of the timestamps that can be sent back:
* `submit-date` for when the circuit was received
* `result-date` for when the circuit had finished running and results were available.
This PR adds another field that gets sent back, `start-date`, for when the circuit actually started to be run.
> Add start-date to fields parsed from job status

- docs/changelog.md
- pytket/extensions/quantinuum/backends/quantinuum.py
Drive-by: fix lint warning by supplying `stacklevel=2` to the other `DeprecationWarning`.
> Emit deprecation warning from `submit_program()`
