docs/changelog.rst
pytket/extensions/quantinuum/backends/quantinuum.py

Add "options" argument to QuantinuumBackend constructor.

---

setup.py

Update the links on pypi containing bugtracker and documentation: like for example on https://pypi.org/project/wasmer/

update pypi links

---

.github/workflows/build_and_test.yml

[infra] Set bash shell when running build-test

---

.github/workflows/check-examples.yml
_metadata.py
docs/changelog.rst
setup.py
tests/backend_test.py

Also bump pytket requirement to 1.9.0rc0.

Add explicit test for conditional phase

---

.github/workflows/build-test
.github/workflows/build_and_test.yml

add upgrade to newest pytket version (including pre release for every run) and run on every push a branch named "runci/..."

add pytket upgrade to build file

---

docs/intro.txt

Small change to the docs to say that ``optimisation_level`` is now set to 2 by default.
Also added a code snippet for clarity. Can remove this if its not needed.

deafult pass docs

---

examples/README.md
examples/check-examples
examples/gen-nb
examples/maintained-notebooks.txt

This should make script generation much easier.

Add script to generate notebooks

---

docs/changelog.rst
pytket/extensions/quantinuum/backends/api_wrappers.py

Make the backend run in worker threads 

---

docs/changelog.rst
pytket/extensions/quantinuum/backends/quantinuum.py
tests/backend_test.py

add kwargs to cost calculation to hand them over to the process circuit function

add kwargs to cost calculation

---

tests/backend_test.py

Update device names in tests

---

examples/Quantinuum_leakage_detection.ipynb

Made a few edits to the intro paragraph, and added a benchmarking example showing better circuit success with leakage detection.

added benchmarking example to notebook

---

.github/workflows/docs/conf.py
.github/workflows/docs/requirements.txt

Similar to https://github.com/CQCL/tket/pull/896
With this change we get:

Generate documentation for Enum values

---

.github/workflows/docs/build-docs
.github/workflows/docs/conf.py

Add source code links as in https://github.com/CQCL/tket/pull/904
This allows you to see the python source code directly from the API docs.

add source links

---

docs/changelog.rst
pytket/extensions/quantinuum/backends/quantinuum.py

Fix to handle multiple classical registers when submitting QIR

---

pytket/extensions/quantinuum/backends/quantinuum.py
tests/integration/backend_test.py

Fixes #200 .
Fixes #211 .
Integration tests run here: https://github.com/CQCL/pytket-quantinuum/actions/runs/6025777087 (all green).

Fix integration tests and handling of null bit list

---

pytket/extensions/quantinuum/backends/api_wrappers.py
pytket/extensions/quantinuum/backends/config.py
pytket/extensions/quantinuum/backends/quantinuum.py
tests/conftest.py
tests/integration/backend_test.py
tests/unit/api_test.py
tests/unit/convert_test.py
tests/unit/offline_backend_test.py

Needed to ensure mypy checks pass with the newly typed version of pytket on `develop`.

Fixes for mypy.

---

.github/workflows/build_and_test.yml
.github/workflows/check-examples.yml
.github/workflows/docs.yml
.github/workflows/lint.yml

Github actions seems to be having issues with v3.

Update to checkout v4.

---

pytket/extensions/quantinuum/__init__.py
pytket/extensions/quantinuum/backends/__init__.py
pytket/extensions/quantinuum/backends/quantinuum.py

Docs fixes

---

tests/integration/backend_test.py

Not sure how this slipped through the net before.

Fix test code for mypy.

---

pytket/extensions/quantinuum/backends/quantinuum.py
tests/unit/convert_test.py

OK since we now require pytket >= 1.19.

Clean up imports.

---

.github/workflows/build-test
pytket/extensions/quantinuum/backends/quantinuum.py
tests/integration/backend_test.py
tests/test-requirements.txt

Reenable QIR submission tests

---

tests/integration/backend_test.py

Also remove "flaky" marker which is not recognized.

Mark expected failures for tests

---

.github/workflows/build_and_test.yml
.github/workflows/check-examples.yml
.github/workflows/docs.yml
.github/workflows/lint.yml

update github actions

---

.github/workflows/build_and_test.yml

add runs of pecos_checks and qa_checks to schedule and push

add runs of pecos_checks and qa_checks to schedule and push

---

.github/workflows/docs/conf.py
pytket/extensions/quantinuum/__init__.py
pytket/extensions/quantinuum/backends/__init__.py
pytket/extensions/quantinuum/backends/api_wrappers.py
pytket/extensions/quantinuum/backends/config.py
pytket/extensions/quantinuum/backends/credential_storage.py
pytket/extensions/quantinuum/backends/federated_login.py
pytket/extensions/quantinuum/backends/leakage_gadget.py
pytket/extensions/quantinuum/backends/quantinuum.py
setup.py
tests/conftest.py
tests/integration/backend_test.py
tests/integration/local_emulator_test.py
tests/unit/api1_test.py
tests/unit/api_test.py
tests/unit/convert_test.py
tests/unit/leakage_detection_test.py
tests/unit/offline_backend_test.py

update copyright 2024

---

setup.py
tests/integration/local_emulator_test.py

Add some more tests for the local emulator (some of them marked as xfail because of issues with pytket-phir).

Add more local-emulator tests

---

docs/changelog.rst
setup.py

This uses the latest version of quantum-pecos with some fixes.

Update to pytket-pecos 0.1.14

---

tests/integration/backend_test.py

This reverts commit 10ad6b83949d7157e7b7339bb527287a13a756d3.

Revert "[test] Remove xfail for QIR noise test. (#355)"

---

docs/changelog.rst
setup.py

This brings in fixes to https://github.com/CQCL/pytket-phir/issues/133 and https://github.com/CQCL/pytket-phir/issues/136 .

Update to pytket-pecos 0.1.17

---

tests/integration/backend_test.py

Extend test for TK2 gate submission

---

pytket/extensions/quantinuum/backends/api_wrappers.py

Fixes a small typo in one of the exceptions for QuantinuumAPIError
N/A

fix: Correct typo in error message

---

tests/integration/backend_test.py

Looks like the wasm tests are now working via qir as well. I have tested this locally in more details.

add wasm test via qir

---

docs/changelog.rst
setup.py
tests/integration/local_emulator_test.py

Update to pytket-pecos 0.1.21

---

.github/workflows/build-test
tests/integration/backend_test.py

Remove pytket-qir install from workflow

clean up ci tests

---

docs/changelog.rst
setup.py

Update to pytket-pecos 0.1.22.

---

docs/changelog.rst
setup.py

Update to pytket-pecos 0.1.23

---

pytket/extensions/quantinuum/backends/quantinuum.py

- Also adds the noisy_simulation parameter for future proofing the local emulation with noise models.

feat: Refactor simulation params into class

---

docs/changelog.rst
setup.py

@cqc-melf Are the two wasm failures a known issue?

Update to pytket_pecos 0.1.25

---

pytket/extensions/quantinuum/backends/quantinuum.py

Solves https://github.com/CQCL/pytket-quantinuum/issues/429

update error message to give jobid

---

docs/changelog.rst
setup.py

update pytket and pytket-qir

---

.github/workflows/issue-to-project.yml

Add new issues to project, not Jira

---

_metadata.py
docs/changelog.rst

Test failures seem to be timeouts.

Create 0.34.1 release

---

.github/workflows/lint.yml
examples/Quantinuum_chemistry_chemically_aware_ucc.ipynb
examples/Quantinuum_n56_ghz_state_fidelity.ipynb
pytket/extensions/quantinuum/backends/calendar_visualisation.py
pytket/extensions/quantinuum/backends/credential_storage.py

update back and pylint version

---

.github/workflows/build_and_test.yml
.github/workflows/issue-to-project.yml
README.md
_metadata.py
docs/changelog.rst
setup.py

Release 0.36.0

---

pytket/extensions/quantinuum/backends/quantinuum.py
setup.py
tests/unit/convert_test.py

update pytket and use pytket scratch_reg_resize_pass

---

docs/changelog.rst
setup.py
tests/integration/backend_test.py

Closes #467 .
Fix piece of test code that was causing test to fail with numpy 2.

Permit numpy 2

---

tests/integration/backend_test.py

maybe fixes https://github.com/CQCL/pytket-quantinuum/issues/484

add tolerance=20 to calendar check

---

tests/integration/backend_test.py

Remove xfail from now-passing test.

---

_metadata.py
docs/changelog.rst
setup.py

Update version and changelog for 0.38.1 release.

---

pytket/extensions/quantinuum/backends/quantinuum.py
tests/integration/backend_test.py

Solves https://github.com/CQCL/pytket-quantinuum/issues/510
and Solves https://github.com/CQCL/pytket-quantinuum/issues/509

fix issues with QIR in cost function and update expected results

---

.github/workflows/build-test
pytket/extensions/quantinuum/backends/calendar_visualisation.py
pytket/extensions/quantinuum/backends/quantinuum.py

And type-check for optional extensions as well.

Remove unused "type: ignore" comments for mypy

---

docs/changelog.rst
pytket/extensions/quantinuum/backends/quantinuum.py
setup.py
tests/integration/backend_test.py

update pytket qir 0.15.0

---

docs/index.rst
pytket/extensions/quantinuum/backends/quantinuum.py

fix: replace usage of deprecated squashing and rebase passes

---

docs/changelog.md
pytket/extensions/quantinuum/__init__.py
pytket/extensions/quantinuum/backends/__init__.py
pytket/extensions/quantinuum/backends/quantinuum.py
tests/integration/local_emulator_test.py

Remove `noise_specs` from local-emulator backends

---

_metadata.py
docs/changelog.md
pytket/extensions/quantinuum/backends/quantinuum.py
setup.py
tests/integration/backend_test.py
tests/integration/local_emulator_test.py

Release 0.45.0 compatible with pytket 2

---

tests/integration/backend_test.py

fix no measure test

---

pytket/extensions/quantinuum/backends/api_wrappers.py
pytket/extensions/quantinuum/backends/credential_storage.py
ruff.toml

change ruff to python version 10

---

docs/changelog.md
pytket/extensions/quantinuum/backends/api_wrappers.py

copied from https://github.com/CQCL/pytket-quantinuum/pull/612

Support requesting raw results

---

tests/integration/backend_test.py

I believe the destruction of the LLVM context inside pytest threads was the cause of the issues.
Closes #170 .
Fixes #617 .

Re-enable garbage collection and move LLVM conversion to a function outside the tests

---

docs/changelog.md
pytket/extensions/quantinuum/backends/quantinuum.py
tests/integration/backend_test.py

Add tests for RNG and shot number.

---

docs/api.md
docs/index.md

add pytket-pecos uv workaround
